import { readFileSync } from "node:fs";
import { relative } from "node:path";

import type { Proposal } from "./discover.js";

/**
 * Delta extraction and PR rendering.
 *
 * Plan rule 4: "Attach the delta to the PR. Reviewers read what changed and why
 * without reverse-engineering the diff. This is our main adoption lever."
 *
 * OpenSpec marks deltas with `## ADDED|MODIFIED|REMOVED Requirements` headings.
 * We read those and render them; we do not author or rewrite them, because
 * OpenSpec owns the design phase.
 */

export const DELTA_KINDS = ["ADDED", "MODIFIED", "REMOVED", "RENAMED"] as const;
export type DeltaKind = (typeof DELTA_KINDS)[number];

export interface DeltaSection {
  readonly kind: DeltaKind;
  /** Heading text after the marker, e.g. "Requirements". */
  readonly heading: string;
  /** Body lines under the heading, trimmed of surrounding blank lines. */
  readonly body: string;
  /** Repo-relative file it came from. */
  readonly file: string;
}

const HEADING = /^(#{2,4})\s+(ADDED|MODIFIED|REMOVED|RENAMED)\b\s*(.*)$/;

/** Parse delta sections out of one markdown document. */
export function parseDelta(markdown: string, file: string): DeltaSection[] {
  const lines = markdown.split("\n");
  const sections: DeltaSection[] = [];

  let current: { kind: DeltaKind; heading: string; level: number; body: string[] } | null = null;

  const flush = (): void => {
    if (current === null) return;
    const body = current.body.join("\n").replace(/^\n+/, "").replace(/\n+$/, "");
    sections.push({ kind: current.kind, heading: current.heading, body, file });
    current = null;
  };

  for (const line of lines) {
    const match = HEADING.exec(line);
    if (match !== null) {
      flush();
      current = {
        kind: (match[2] ?? "ADDED") as DeltaKind,
        heading: (match[3] ?? "").trim(),
        level: (match[1] ?? "##").length,
        body: [],
      };
      continue;
    }

    if (current !== null) {
      // A heading at the same or shallower level ends the section.
      const other = /^(#{1,6})\s+/.exec(line);
      if (other !== null && (other[1] ?? "").length <= current.level) {
        flush();
        continue;
      }
      current.body.push(line);
    }
  }

  flush();
  return sections;
}

/** Every delta section across a proposal's files. */
export function deltaFor(root: string, proposal: Proposal): DeltaSection[] {
  const out: DeltaSection[] = [];
  for (const path of proposal.files) {
    let text: string;
    try {
      text = readFileSync(path, "utf8");
    } catch {
      continue;
    }
    out.push(...parseDelta(text, relative(root, path).split(/[\\/]/).join("/")));
  }
  return out;
}

const EMOJI: Readonly<Record<DeltaKind, string>> = {
  ADDED: "+",
  MODIFIED: "~",
  REMOVED: "-",
  RENAMED: "→",
};

export interface RenderOptions {
  /** Wrap in the marker comments `keel pr delta --update` looks for. */
  readonly withMarkers?: boolean;
}

export const DELTA_BEGIN = "<!-- keel:delta:begin -->";
export const DELTA_END = "<!-- keel:delta:end -->";

/**
 * Render a proposal's delta as PR-comment markdown.
 *
 * Deliberately compact. A delta longer than the diff defeats the purpose, and
 * the size cap already says so — this rendering leads with a one-line summary
 * so a reviewer gets the shape before deciding to read further.
 */
export function renderDelta(
  proposal: Proposal,
  sections: readonly DeltaSection[],
  options: RenderOptions = {},
): string {
  const parts: string[] = [];
  if (options.withMarkers === true) parts.push(DELTA_BEGIN);

  parts.push(`## Spec delta — \`${proposal.id}\``);
  parts.push("");

  if (sections.length === 0) {
    parts.push(
      "_No delta markers found._ Add `## ADDED Requirements`, `## MODIFIED Requirements` " +
        "or `## REMOVED Requirements` sections to the change's spec files so reviewers can " +
        "see what changed without reverse-engineering the diff.",
    );
  } else {
    const counts = new Map<DeltaKind, number>();
    for (const section of sections) counts.set(section.kind, (counts.get(section.kind) ?? 0) + 1);
    const summary = [...counts.entries()]
      .map(([kind, n]) => `${EMOJI[kind]} ${n} ${kind.toLowerCase()}`)
      .join(" · ");

    parts.push(summary);
    parts.push("");
    parts.push(`${proposal.lineCount} spec lines · status \`${proposal.status}\``);
    parts.push("");

    for (const section of sections) {
      parts.push(
        `### ${EMOJI[section.kind]} ${section.kind}${section.heading === "" ? "" : ` ${section.heading}`}`,
      );
      parts.push("");
      if (section.body !== "") {
        parts.push(section.body);
        parts.push("");
      }
      parts.push(`<sub>${section.file}</sub>`);
      parts.push("");
    }
  }

  parts.push("<sub>Generated by `keel spec delta`.</sub>");
  if (options.withMarkers === true) parts.push(DELTA_END);
  return parts.join("\n");
}

/**
 * Splice a rendered delta into an existing PR body, replacing any previous one.
 *
 * Same managed-marker discipline as CLAUDE.md: anything a human wrote outside
 * the markers survives.
 */
export function mergeIntoBody(body: string, rendered: string): string {
  const start = body.indexOf(DELTA_BEGIN);
  const end = body.indexOf(DELTA_END);

  if (start >= 0 && end > start) {
    return `${body.slice(0, start)}${rendered}${body.slice(end + DELTA_END.length)}`;
  }
  const separator = body.trim() === "" ? "" : "\n\n---\n\n";
  return `${body}${separator}${rendered}\n`;
}
